### PR TITLE
Add Language (Rust)

### PR DESCRIPTION
**Pull request by jdekim43**

### CODE REVIEW

**Comment by jdekim43** [comment]
Conflict validators and Validators at cosmos/staking/v1beta1/authz.proto because 'oneof validators' renamed to 'enum Validators'. (Apply Camelcase automatically)
So i did ignored that.

Does anyone know how to fix that?

```
message StakeAuthorization {
  option (cosmos_proto.implements_interface) = "Authorization";

  // max_tokens specifies the maximum amount of tokens can be delegate to a validator. If it is
  // empty, there is no spend limit and any amount of coins can be delegated.
  cosmos.base.v1beta1.Coin max_tokens = 1 [(gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coin"];
  // validators is the oneof that represents either allow_list or deny_list
  oneof validators {
    // allow_list specifies list of validator addresses to whom grantee can delegate tokens on behalf of granter's
    // account.
    Validators allow_list = 2;
    // deny_list specifies list of validator addresses to whom grantee can not delegate tokens.
    Validators deny_list = 3;
  }
  // Validators defines list of validator addresses.
  message Validators {
    repeated string address = 1;
  }
  // authorization_type defines one of AuthorizationType.
  AuthorizationType authorization_type = 4;
}
```

**Comment by petes-fan-club** [comment]
fyi.. I was building something similar, but I didn't use 'prost', but the native protoc stuff
it's available here - https://github.com/PFC-Validator/terra.proto/tree/main/rust

not claiming anything, just a different approach.

**Comment by petes-fan-club** [comment]
btw.. when I try to import this I get

error: `proc-macro` crate types currently cannot export any items other than functions tagged with `#[proc_macro]`, `#[proc_macro_derive]`, or `#[proc_macro_attribute]`
 --> C:\Users\ihols\.cargo\git\checkouts\terra.proto-bac5e53a5699bb91\176ce98\rust\src\lib.rs:1:1
  |
1 | pub mod generated;
  | ^^^^^^^^^^^^^^^^^^

****

**Comment by jdekim43** [comment]
Thanks @petes-fan-club for your error report. I fixed it.

I tried other proto compilier (e.g. rust-protobuf). But they have same issue too.

I see that PFC-Validator rust builds has not 'cosmos/staking/v1beta1/authz.proto'.
Do you have not see same my problem on your builds?
(I try to build your codes, but failed caused by `".tendermint.p2p.NodeInfo" is not defined.`)

**Comment by petes-fan-club** [comment]
it looks like I only compile a subset of cosmos sdk.
it does build as a dependency on windows & linux, although you do need a setting in .cargo/config as the submodules are via 'git' not https.

https://github.com/PFC-Validator/constellation-web-socket, which is part of - https://github.com/PFC-Validator/constellation
uses it.. but it is more analytics... I'll add the missing cosmos prototypes, and look what you mean by failing compile.

the 'terra' stuff is generated, and then edited to fix an issue with 'coins'

**Comment by petes-fan-club** [comment]
but tbh.. if yours works, I'll move to it.

**Comment by petes-fan-club** [comment]
ok.. I understand what you mean.
the build isn't automated. some of the imports need to be tweaked.
I added a 'readme' and added authz to the list of cosmos types as well.

**Comment by PFC-developer** [comment]
hi Paul.

I am using this library now in my code, and it appears to work fine.
are you still waiting on the issue of StakeAuthorization  above before you merge this?

**Comment by emidev98** [comment]
Hey @PFC-developer, sorry for the late response, this changes will be included here https://github.com/terra-money/terra.proto/pull/22

**Pull request closed without merging**
